-- CreateTable
CREATE TABLE "LOJA" (
    "ID_LOJA" SERIAL NOT NULL,
    "NOME_SOCIAL" VARCHAR(100) NOT NULL,
    "NOME_FANTASIA" VARCHAR(100) NOT NULL,
    "LOGO" VARCHAR(1000),
    "CNPJ" CHAR(14) NOT NULL,
    "TELEFONE_COMERCIAL" CHAR(11) NOT NULL,
    "ENDERECO" VARCHAR(300) NOT NULL,

    CONSTRAINT "LOJA_pkey" PRIMARY KEY ("ID_LOJA")
);

-- CreateTable
CREATE TABLE "DESCONTOS" (
    "ID_DESCONTO" SERIAL NOT NULL,
    "TITULO" VARCHAR(200) NOT NULL,
    "FOTO_ITEM" VARCHAR(1000) NOT NULL,
    "VALOR_DESCONTO" DECIMAL(10,2) NOT NULL,
    "DESCRICAO" VARCHAR(500) NOT NULL,
    "CATEGORIA" VARCHAR(100) NOT NULL,
    "ID_LOJA" INTEGER NOT NULL,

    CONSTRAINT "DESCONTOS_pkey" PRIMARY KEY ("ID_DESCONTO")
);

-- CreateTable
CREATE TABLE "CUPONS" (
    "ID_CUPOM" SERIAL NOT NULL,
    "TITULO" VARCHAR(200) NOT NULL,
    "DESCRICAO" VARCHAR(500) NOT NULL,
    "CODIGO" VARCHAR(20) NOT NULL,
    "VALIDADE" DATE NOT NULL,
    "ID_LOJA" INTEGER NOT NULL,

    CONSTRAINT "CUPONS_pkey" PRIMARY KEY ("ID_CUPOM")
);

-- CreateTable
CREATE TABLE "USUARIO" (
    "ID_USUARIO" SERIAL NOT NULL,
    "NOME_COMPLETO" VARCHAR(100) NOT NULL,
    "SENHA" VARCHAR(15) NOT NULL,
    "TELEFONE" CHAR(11),
    "CEP" CHAR(8),
    "EMAIL" VARCHAR(150) NOT NULL,
    "ENDERECO" VARCHAR(300) NOT NULL,

    CONSTRAINT "USUARIO_pkey" PRIMARY KEY ("ID_USUARIO")
);

-- AddForeignKey
ALTER TABLE "DESCONTOS" ADD CONSTRAINT "DESCONTOS_ID_LOJA_fkey" FOREIGN KEY ("ID_LOJA") REFERENCES "LOJA"("ID_LOJA") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CUPONS" ADD CONSTRAINT "CUPONS_ID_LOJA_fkey" FOREIGN KEY ("ID_LOJA") REFERENCES "LOJA"("ID_LOJA") ON DELETE RESTRICT ON UPDATE CASCADE;
